name: Continuous Integration
'on':
  push:
    branches-ignore:
      - main
jobs:
  build:
    name: Lint [feature/fix]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18.x
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/workflow-telemetry-action@v1
      - name: Lint
        run: yarn lint
      - name: Circular Dependencies Check
        run: yarn test:circular