name: Publish


on:
  push:
    branches:
      - main

concurrency: main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0

    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        registry-url: 'https://registry.npmjs.org'
        scope: "@valculator"
        always-auth: true

    - name: Version
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor}}@users.noreply.github.com"
        npx lerna version --conventional-commits --yes
        
    - name: Install Dependencies
      run: yarn install
    
    - name: Build
      run: yarn build

    - name: Publish
      run: npx lerna publish from-git --yes
      env: 
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}