name: Publish

on:
  push:
    branches:
      - main

concurrency: main
permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        registry-url: 'https://registry.npmjs.org'
        scope: '@valculator'
        always-auth: true

    - name: Install Dependencies
      run: yarn install

    - name: Build
      run: yarn build

    - name: Publish
      run: yarn lerna publish from-package --yes
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
