name: Publish
concurrency: main
permissions: write-all

on:
  push:
    branches: [ config/lerna ]
  pull_request:
    branches: '*'

jobs:
  # quality:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: 
  #         - 18.x

  #   steps:
  #     - name: Checkout source code
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #         ref: ${{ github.ref }}
  #         token: ${{ secrets.GITHUB_TOKEN }}
      
  #     - name: Use Node.js 18.x
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 18.x 

  #     - name: Install Dependencies
  #       run: yarn install
      
  #     - name: Lint
  #       run: yarn lint
      
  #     - name: Circular Dependencies Check
  #       run: yarn test:circular
  
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/config/lerna' }}
    # needs: [quality]
    steps: 
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0

    - name: Use Node.js 18.x
      uses: actions/setup-node@v2
      with:
        node-version: 18.x
        registry-url: 'https://registry.npmjs.org'
        scope: "@stage-tech"
        always-auth: true

    - name: Version and Publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor}}@users.noreply.github.com"
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
        npx lerna version --conventional-commits --yes
        npx lerna publish from-git --yes
      

    # - run: yarn install
    # - run: yarn semantic-release
    #   env: 
    #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}